# Generated by Django 4.2.1 on 2023-07-31 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_remove_team_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='voting_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voting.votingevent'),
            preserve_default=False,
        ),
    ]
