# Generated by Django 4.2.1 on 2023-07-31 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_remove_team_created_at_profile_team_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.ImageField(blank=True, null=True, upload_to='team_flags/')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='team',
            name='voting_event',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='team',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='competitor',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.team'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='voting_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.votingevent'),
        ),
        migrations.AddField(
            model_name='vote',
            name='competitor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voting.competitor'),
            preserve_default=False,
        ),
    ]
